### PR TITLE
Added warning when `rm -rf ~`  is mentioned 

### PR DESCRIPTION
**Pull request by Bikoil**
I changed `tux/utils/functions.py` in the `harmful_command_pattern` so that it's noticed that this is also a harmful command like `sudo rm -rf /`

## Summary by Sourcery

This pull request updates the harmful command detection pattern to recognize `rm -rf ~` as a harmful command, enhancing the safety checks in the utility functions.

- **Enhancements**:
    - Extended the harmful command detection pattern to include `rm -rf ~` as a harmful command.

### CODE REVIEW

**Comment by Bikoil** [comment]
Changed  `tux/utils/functions.py` once again so it gives warnings not only for dangerous linux commands but also windows commands :P

**Review by electron271 — CHANGES_REQUESTED** [review]
none of us really know about windows, in the long run i feel like this will just overcomplicate things

**Comment by basil-squared** [comment]
@electron271
I don't think it will be an issue. i understood the commands just fine, they seem about right and it makes sense to have the same layer of protection for that OS as well.

on the other hand, windows does an excellent job at hand-holding the user to make sure they don't bork anything. so it may not be necessary, but definitely nice to have at the end of the day.

**Comment by electron271** [comment]
in my opinion this is still out of scope

**Comment by electron271** [comment]
i will merge it however i at least will not be maintaining the windows detection

**Review by electron271 — APPROVED** [review]

**Comment by Bikoil** [comment]
@electron271 @FluxC0 yay thank youu :)

**Pull request merged**
