### PR TITLE
changed the name of the eval command to the run command.

### PR DESCRIPTION
**Pull request by HikariNee**
must be merged prior to #176

### CODE REVIEW

**Review by electron271 — CHANGES_REQUESTED** [review]
conflicts with the old run command which should be renamed to eval

please also rename the file

**Comment by HikariNee** [comment]
> please also rename the file

done.

**Comment by electron271** [comment]
this will also conflict so ideally the pr would be made out of the other pr then merged into the run command pr

**Comment by electron271** [comment]
done upstream on the pr

**Pull request closed without merging**
