### PR TITLE
added simple little before and after when editing a snippet (unfinished)

### PR DESCRIPTION
**Pull request by meatsnails**
image

## Summary by Sourcery

Enhance the snippet editing functionality by showing the previous content alongside the new content in the confirmation message when a snippet is edited.

Enhancements:
- Display the previous content of a snippet alongside the new content when a snippet is edited.

### CODE REVIEW

**Comment by meatsnails** [comment]
i'll be changing this to embeds later on but currently this is what i doing for now

**Review by electron271 — CHANGES_REQUESTED** [review]
very spammy with large snippets, at least truncate each to 50 chars

**Comment by meatsnails** [comment]
> very spammy with large snippets, at least truncate each to 50 chars

added that for now

**Comment by meatsnails** [comment]
> > very spammy with large snippets, at least truncate each to 50 chars
> 
> added that for now

as kaizen said ill prob add buttons to view the before and after once i get to adding embeding

**Review by electron271 — APPROVED** [review]
is this ready for merge?

**Comment by meatsnails** [comment]
kaizen wants me to add an embed and buttons for viewing the before and after before merging it so i marked it as unfinished

**Comment by electron271** [comment]
ok

**Pull request closed without merging**
